### ISSUE TITLE
undefined method 'transform'

### ISSUE THREAD

**Issue by jckfa** [samvincent/jekyll-haml#19]
I'm getting the following error when I build:
`jekyll 3.3.0 | Error:  undefined method 'transform' for #<Jekyll::Renderer:0x007fd77d960f58>`

I don't get the error and my site builds successfully when I comment out the jekyll-haml gem.

**Comment by jckfa** [comment]
has to do with jekyll-haml/ext/convertible

**Comment by samvincent** [comment]
Patches welcome. I'm not maintaining this package at the moment.

**Comment by schoenwaldnils** [comment]
I have the same error.

**Comment by svpersteve** [comment]
It's not compatible with Jekyll 3.3.0, somebody would need to submit a pull request for a patch to fix this @jckfa ☹️

**Comment by joallard** [comment]
I don't remember much, but I don't think I got it working. Here's where I got:

![screen shot 2016-12-03 at 13 48 01](https://cloud.githubusercontent.com/assets/949482/20861464/354563c6-b95f-11e6-9a73-ba2175231013.png)

Yep, that's it. I was hoping they'd respond upstream.

**Comment by joallard** [comment]
Oh wait yeah, that was a workaround pending jekyll/jekyll#5052, which stopped the errors, but then JH just had no effect on the Haml files, I couldn't figure out why, and I moved on.

**Comment by samvincent** [comment]
`jekyll-haml (0.1.5)` released that should close this. Thanks @reivaxm and @joallard.
